# Sidebar navigation

- label: "About"
  link: "/"
- label: Projects
  items:
    - label: "Sqwak"
      link: "/sqwak"
    - label: "Yogoflow"
      link: "/yogoflow"
    - label: "react-chat-window"
      link: "/react-chat-window"
    - label: "seam-carving"
      link: "/seam-carving"
    - label: "Mr. Makes a Word"
      link: "/mr-makes-a-word"
    - label: "Projection Mapping"
      link: "/projection-mapping"
- label: More
  items:
    - label: LinkedIn
      link: https://www.linkedin.com/in/dhsoftware/
    - label: "Motion Design"
      link: https://vimeo.com/823151596
    - label: "Github"
      link: https://github.com/jpedroschmitz/rocketdocs
